(()=>{
  const POSITION_LIMITS={GKP:2,DEF:5,MID:5,FWD:3};
  const AUTO_ACCEPT_SCORE=110;
  const AUTO_ACCEPT_MARGIN=25;
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9.]+/g,' ').trim();
  const lev=(a,b)=>{a=norm(a);b=norm(b);const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]};
  function status(html,kind='info'){let el=document.getElementById('ocrStatus');if(!el){el=document.createElement('div');el.id='ocrStatus';const anchor=document.querySelector('.team-intro');if(anchor)anchor.insertAdjacentElement('afterend',el)}if(!el)return;el.className=`ocr-status ${kind}`;el.innerHTML=html}
  function availablePlayers(){return (window.fplApp?.getPlayers?.()||[]).map(p=>({id:p.id,name:p.name,team:p.team,price:p.price,position:p.position}))}
  function parsePrice(line){return [...String(line||'').matchAll(/(?:£\s*)?([0-9]{1,2}(?:[.,][0-9])?)(?:\s*m)?/gi)].map(m=>Number(m[1].replace(',','.'))).filter(v=>v>=3.5&&v<=20)}
  function nameScore(lineName,playerName){const l=norm(lineName),p=norm(playerName);if(!l||!p)return 0;if(l.includes(p))return 1;const surname=p.split(' ').pop();let best=0;for(const part of l.split(' ')){if(part.length<3)continue;const d=lev(part,surname);const allowed=surname.length>=8?2:1;if(d<=allowed)best=Math.max(best,.78-d*.12)}return best}
  function detectPlayers(text,players){const lines=String(text||'').split(/\n+/).map((raw,i)=>({i,raw,n:norm(raw)})).filter(x=>x.n);const claims=[];for(const line of lines){const context=[lines[line.i-1]?.raw,lines[line.i+1]?.raw].filter(Boolean).join(' ');const ranked=players.map(p=>{let score=nameScore(line.n,p.name)*100;if(score<55)return null;const prices=parsePrice(`${line.raw} ${context}`);if(prices.length){const d=Math.min(...prices.map(v=>Math.abs(v-p.price)));if(d<.01)score+=35;else if(d<=.1)score+=25;else if(d>.5)score-=15}const ctx=norm(`${line.raw} ${context}`);if(ctx.includes(norm(p.team)))score+=25;return{p,score}}).filter(Boolean).sort((a,b)=>b.score-a.score);if(!ranked.length)continue;const best=ranked[0],second=ranked[1],margin=best.score-(second?.score||0);claims.push({id:best.p.id,name:best.p.name,team:best.p.team,price:best.p.price,position:best.p.position,line:line.i,score:best.score,margin})}claims.sort((a,b)=>b.score-a.score||b.margin-a.margin||a.line-b.line);const used=new Set(),counts={GKP:0,DEF:0,MID:0,FWD:0},accepted=[],suggested=[];for(const c of claims){if(used.has(c.id))continue;used.add(c.id);const confident=c.score>=AUTO_ACCEPT_SCORE&&c.margin>=AUTO_ACCEPT_MARGIN;if(!confident){suggested.push(c);continue}if(!POSITION_LIMITS[c.position]||counts[c.position]>=POSITION_LIMITS[c.position]){suggested.push(c);continue}counts[c.position]++;accepted.push(c)}accepted.sort((a,b)=>a.line-b.line);return{accepted:accepted.slice(0,15),suggested:suggested.slice(0,10)}}
  async function fillSlots(matches){const players=availablePlayers();const slotsByPos={GKP:[],DEF:[],MID:[],FWD:[]};for(let i=0;i<15;i++){const p=players.find(x=>String(x.id)===String(window.fplApp?.getTeam?.()?.slots?.[i]?.playerId));if(p&&slotsByPos[p.position])slotsByPos[p.position].push(i)}const usedSlots=new Set();for(const m of matches){let target=null;for(let i=0;i<15;i++){if(usedSlots.has(i))continue;const team=window.fplApp?.getTeam?.();const current=team?.slots?.[i]?.playerId;if(!current){target=i;break}}if(target==null)break;window.fplApp?.setPlayerSlot?.(target,m.id);usedSlots.add(target)}window.fplApp?.render?.()}
  async function process(file){if(!file||!file.type.startsWith('image/')){status('<strong>Could not read that file.</strong> Please choose an image screenshot.','error');return}if(!window.Tesseract){status('<strong>Screenshot reader did not load.</strong> Refresh the page and try again.','error');return}status('<strong>Reading screenshot…</strong> Only high-confidence matches will be added automatically.');try{const worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')status(`<strong>Reading screenshot…</strong> ${Math.round((m.progress||0)*100)}%`)}});const result=await worker.recognize(file);await worker.terminate();const {accepted,suggested}=detectPlayers(result?.data?.text||'',availablePlayers());if(!accepted.length){status('<strong>No players met the automatic confidence threshold.</strong> Use the positional editor to enter them manually.','warn');return}await fillSlots(accepted);const acceptedText=accepted.map(x=>`${x.name} (${x.position}, ${x.team}, £${x.price.toFixed(1)}m)`).join(', ');const suggestionText=suggested.length?` Lower-confidence suggestions not added: ${suggested.slice(0,5).map(x=>x.name).join(', ')}.`:'';status(`<strong>Auto-added ${accepted.length} high-confidence player${accepted.length===1?'':'s'}.</strong> ${acceptedText}.${suggestionText} Please verify against the screenshot.` ,accepted.length>=10?'success':'warn')}catch(err){console.error(err);status('<strong>Screenshot reading failed.</strong> Enter the squad manually using the positional rows.','error')}}
  document.addEventListener('change',e=>{if(e.target?.id==='teamScreenshot'){const f=e.target.files?.[0];if(f)setTimeout(()=>process(f),60)}})
})();