(()=>{
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9.]+/g,' ').trim();
  const lev=(a,b)=>{a=norm(a);b=norm(b);const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]};
  function status(html,kind='info'){let el=document.getElementById('ocrStatus');if(!el){el=document.createElement('div');el.id='ocrStatus';const anchor=document.querySelector('.team-intro');if(anchor)anchor.insertAdjacentElement('afterend',el)}if(!el)return;el.className=`ocr-status ${kind}`;el.innerHTML=html}
  function availablePlayers(){return (window.fplApp?.getPlayers?.()||[]).map(p=>({id:p.id,name:p.name,team:p.team,price:p.price}))}
  function parsePrice(line){return [...String(line||'').matchAll(/(?:£\s*)?([0-9]{1,2}(?:[.,][0-9])?)(?:\s*m)?/gi)].map(m=>Number(m[1].replace(',','.'))).filter(v=>v>=3.5&&v<=20)}
  function nameScore(lineName,playerName){const l=norm(lineName),p=norm(playerName);if(!l||!p)return 0;if(l.includes(p))return 1;const surname=p.split(' ').pop();let best=0;for(const part of l.split(' ')){if(part.length<3)continue;const d=lev(part,surname);const allowed=surname.length>=8?2:1;if(d<=allowed)best=Math.max(best,.78-d*.12)}return best}
  function detectPlayers(text,players){const lines=String(text||'').split(/\n+/).map((raw,i)=>({i,raw,n:norm(raw)})).filter(x=>x.n);const claims=[];for(const line of lines){const context=[lines[line.i-1]?.raw,lines[line.i+1]?.raw].filter(Boolean).join(' ');const ranked=players.map(p=>{let score=nameScore(line.n,p.name)*100;if(score<55)return null;const prices=parsePrice(`${line.raw} ${context}`);if(prices.length){const d=Math.min(...prices.map(v=>Math.abs(v-p.price)));if(d<.01)score+=35;else if(d<=.1)score+=25;else if(d>.5)score-=15}const ctx=norm(`${line.raw} ${context}`);if(ctx.includes(norm(p.team)))score+=25;return{p,score}}).filter(Boolean).sort((a,b)=>b.score-a.score);if(ranked.length&&(ranked[0].score>=82||ranked[0].score-(ranked[1]?.score||0)>=18))claims.push({id:ranked[0].p.id,name:ranked[0].p.name,team:ranked[0].p.team,price:ranked[0].p.price,line:line.i,score:ranked[0].score})}claims.sort((a,b)=>a.line-b.line||b.score-a.score);const used=new Set(),out=[];for(const c of claims){if(used.has(c.id))continue;used.add(c.id);out.push(c)}return out.slice(0,15)}
  async function fillSlots(matches){matches.slice(0,15).forEach((m,i)=>window.fplApp?.setPlayerSlot?.(i,m.id));window.fplApp?.render?.()}
  async function process(file){if(!file||!file.type.startsWith('image/')){status('<strong>Could not read that file.</strong> Please choose an image screenshot.','error');return}if(!window.Tesseract){status('<strong>Screenshot reader did not load.</strong> Refresh the page and try again.','error');return}status('<strong>Reading screenshot…</strong>');try{const worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')status(`<strong>Reading screenshot…</strong> ${Math.round((m.progress||0)*100)}%`)}});const result=await worker.recognize(file);await worker.terminate();const matches=detectPlayers(result?.data?.text||'',availablePlayers());if(!matches.length){status('<strong>No players were confidently detected.</strong> Use Team ID or enter players manually.','warn');return}await fillSlots(matches);status(`<strong>Detected ${matches.length} player${matches.length===1?'':'s'}.</strong> ${matches.map(x=>`${x.name} (${x.team}, £${x.price.toFixed(1)}m)`).join(', ')}. Please verify the squad.` ,matches.length>=11?'success':'warn')}catch(err){console.error(err);status('<strong>Screenshot reading failed.</strong> Use Team ID or enter the squad manually.','error')}}
  document.addEventListener('change',e=>{if(e.target?.id==='teamScreenshot'){const f=e.target.files?.[0];if(f)setTimeout(()=>process(f),60)}})
})();