(()=>{
  const KEY='fpl-entry-id';
  let busy=false;
  function inject(){
    const intro=document.querySelector('.team-intro');if(!intro||document.getElementById('teamIdPanel'))return;
    const panel=document.createElement('section');panel.id='teamIdPanel';panel.className='team-id-panel';
    panel.innerHTML=`<div class="team-id-copy"><h3>Load from FPL Team ID <span class="recommended">Recommended</span></h3><p>Enter your FPL entry ID to load the latest publicly available squad directly from the official FPL API.</p></div><div class="team-id-controls"><input id="teamIdInput" inputmode="numeric" pattern="[0-9]*" placeholder="e.g. 1234567" value="${localStorage.getItem(KEY)||''}"><button id="loadTeamId">Load my team</button></div><div id="teamIdStatus" class="team-id-status"></div>`;
    intro.insertAdjacentElement('afterend',panel);document.getElementById('loadTeamId').onclick=load;document.getElementById('teamIdInput').addEventListener('keydown',e=>{if(e.key==='Enter')load()});
  }
  function status(msg,kind='info'){const el=document.getElementById('teamIdStatus');if(!el)return;el.className=`team-id-status ${kind}`;el.innerHTML=msg}
  async function load(){if(busy)return;const input=document.getElementById('teamIdInput');const entry=input?.value?.trim();if(!entry||!/^[0-9]+$/.test(entry)){status('<strong>Enter a valid numeric FPL Team ID.</strong>','error');return}busy=true;localStorage.setItem(KEY,entry);status('<strong>Loading your squad from FPL…</strong>');try{const r=await fetch(`/api/team?entry=${encodeURIComponent(entry)}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not load team');if(!data.publicPicksAvailable){status(`<strong>${data.teamName||'Team found'}, but no public picks are available yet.</strong> ${data.message||''}`,'warn');return}if(!window.fplApp?.setTeamFromPicks)throw new Error('App state is not ready');window.fplApp.setTeamFromPicks(data);setTimeout(()=>{inject();status(`<strong>Loaded ${data.teamName||'your team'} from GW${data.event}.</strong> Starting XI, bench, captain and vice-captain were populated from the official FPL API.`,'success')},0)}catch(e){status(`<strong>Could not load that team.</strong> ${e.message||''}`,'error')}finally{busy=false}}
  const observer=new MutationObserver(()=>inject());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',inject);setTimeout(inject,300);
})();